### ISSUE TITLE
[TS]: Fix Component Props declarations

### ISSUE THREAD

**Issue by abnersajr** [grommet/grommet#4978]
Pay attention to rules for migration at the end of the issue.

### Expected Behavior

Be able to import and extend the `<component>Props` correctly, bringing the ` JSX.IntrinsicElements` props together.

### Actual Behavior

Components have theirs on `<component>Props` combined with ` JSX.IntrinsicElements` being exported using the `declare` block. The import of `<component>Props` doesn't have all the props defined in the `declare` block.

References:
https://github.com/grommet/grommet/pull/4909
https://github.com/grommet/grommet/issues/4976

### Proposed Solution

As discussed in the PR: https://github.com/grommet/grommet/pull/4909,
We need to check which components follow the pattern of combining the props on `declare` blocks.
A second item is that many components are defined as `React.ComponentClass` but can be modified to `React.FC`.

That being said, we should start refining these declarations following the examples below, where we create and export an extended version of the props instead of removing the actual export:

```ts
export interface LayerProps {...}
export type LayerPropsExtended = LayerProps & JSX.IntrinsicElements['div'] 

// React.FC or React.componentClass must be evaluated to see if the change is possible.
// Preference to use React.FC
declare const Layer: React.FC<LayerPropsExtended>;

export { Layer };
```
```ts
// another example
export interface TextInputProps { ... };

export interface TextInputExtendedProps extends Omit<
JSX.IntrinsicElements['input'],
'onSelect' | 'size' | 'placeholder'
>, TextInputProps {};

declare const TextInput: React.FC<TextInputExtendedProps>;

export { TextInput };
```

### Roadmap

Thanks to @Isaius for check and get this list for us.

 These do not extend `JSX.IntrinscElements` in their props interface but in the `declare` block.
 
- [ ] [Accordion](https://github.com/grommet/grommet/blob/master/src/js/components/Accordion/index.d.ts)
- [ ] [AccordionPanel](https://github.com/grommet/grommet/blob/master/src/js/components/AccordionPanel/index.d.ts)
- [ ] [Anchor](https://github.com/grommet/grommet/blob/master/src/js/components/Anchor/index.d.ts)
- [ ] [Carroussel](https://github.com/grommet/grommet/blob/master/src/js/components/Carousel/index.d.ts) [ComponentClass]
- [ ] [CheckBox](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox/index.d.ts)
- [ ] [CheckBoxGroup](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBoxGroup/index.d.ts)
- [ ] [Clock](https://github.com/grommet/grommet/blob/master/src/js/components/Clock/index.d.ts)
- [ ] [Collapsible](https://github.com/grommet/grommet/blob/master/src/js/components/Collapsible/index.d.ts)
- [ ] [DataTable](https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/index.d.ts)
- [ ] [Diagram](https://github.com/grommet/grommet/blob/master/src/js/components/Diagram/index.d.ts)
- [ ] [Distribution](https://github.com/grommet/grommet/blob/master/src/js/components/Distribution/index.d.ts)
- [ ] [DropButton](https://github.com/grommet/grommet/blob/master/src/js/components/DropButton/index.d.ts)
- [ ] [FileInput](https://github.com/grommet/grommet/blob/master/src/js/components/FileInput/index.d.ts)
- [ ] [FormField](https://github.com/grommet/grommet/blob/master/src/js/components/FormField/index.d.ts)
- [ ] [Grid](https://github.com/grommet/grommet/blob/master/src/js/components/Grid/index.d.ts)
- [ ] [Grommet](https://github.com/grommet/grommet/blob/master/src/js/components/Grommet/index.d.ts)
- [ ] [Heading](https://github.com/grommet/grommet/blob/master/src/js/components/Heading/index.d.ts)
- [ ] [Image](https://github.com/grommet/grommet/blob/master/src/js/components/Image/index.d.ts)
- [ ] [Layer](https://github.com/grommet/grommet/blob/master/src/js/components/Layer/index.d.ts)
- [ ] [List](https://github.com/grommet/grommet/blob/master/src/js/components/List/index.d.ts)
- [ ] [Markdown](https://github.com/grommet/grommet/blob/master/src/js/components/Markdown/index.d.ts)
- [ ] [MaskedInput](https://github.com/grommet/grommet/blob/master/src/js/components/MaskedInput/index.d.ts)
- [ ] [Paragraph](https://github.com/grommet/grommet/blob/master/src/js/components/Paragraph/index.d.ts)
- [ ] [RadioButton](https://github.com/grommet/grommet/blob/master/src/js/components/RadioButton/index.d.ts)
- [ ] [RadioButtonGroup](https://github.com/grommet/grommet/blob/master/src/js/components/RadioButtonGroup/index.d.ts)
- [ ] [RangeInput](https://github.com/grommet/grommet/blob/master/src/js/components/RangeInput/index.d.ts)
- [ ] [RangeSelector](https://github.com/grommet/grommet/blob/master/src/js/components/RangeSelector/index.d.ts)
- [ ] [SideBar](https://github.com/grommet/grommet/blob/master/src/js/components/Sidebar/index.d.ts)
- [ ] [Stack](https://github.com/grommet/grommet/blob/master/src/js/components/Stack/index.d.ts)
- [ ] [Tab](https://github.com/grommet/grommet/blob/master/src/js/components/Tab/index.d.ts)
- [ ] [Table](https://github.com/grommet/grommet/blob/master/src/js/components/Table/index.d.ts)
- [ ] [TableBody](https://github.com/grommet/grommet/blob/master/src/js/components/TableBody/index.d.ts)
- [ ] [TableCell](https://github.com/grommet/grommet/blob/master/src/js/components/TableCell/index.d.ts)
- [ ] [TableFooter](https://github.com/grommet/grommet/blob/master/src/js/components/TableFooter/index.d.ts)
- [ ] [TableHeader](https://github.com/grommet/grommet/blob/master/src/js/components/TableHeader/index.d.ts)
- [ ] [TableRow](https://github.com/grommet/grommet/blob/master/src/js/components/TableRow/index.d.ts)
- [ ] [Tabs](https://github.com/grommet/grommet/blob/master/src/js/components/Tabs/index.d.ts)
- [ ] [Text](https://github.com/grommet/grommet/blob/master/src/js/components/Text/index.d.ts)
- [ ] [TextArea](https://github.com/grommet/grommet/blob/master/src/js/components/TextArea/index.d.ts)
- [ ] [Video](https://github.com/grommet/grommet/blob/master/src/js/components/Video/index.d.ts)
- [ ] [WorldMap](https://github.com/grommet/grommet/blob/master/src/js/components/WorldMap/index.d.ts)
 
 These are OK, but do not follow the pattern, using Type instead interface:
 
- [ ] [Box](https://github.com/grommet/grommet/blob/master/src/js/components/Box/index.d.ts)
- [ ] [Button](https://github.com/grommet/grommet/blob/master/src/js/components/Button/index.d.ts)
- [ ] [Calendar](https://github.com/grommet/grommet/blob/master/src/js/components/Calendar/index.d.ts)
- [ ] [Drop](https://github.com/grommet/grommet/blob/master/src/js/components/Drop/index.d.ts)
 
 Only ComponentClass, but not wrong:
 
- [ ] [Chart](https://github.com/grommet/grommet/blob/master/src/js/components/Chart/index.d.ts)

### Rules for Migration

- Pick a maximum of **4 components** at the same time
- Comment which one you will work
- Work is done! Create the PR with a **maximum of 4 components per PR**
- Wait for the review and the merge. After merged, you can pick new ones.

**Comment by Isaius** [comment]
How about we make an list of components that need be changed, for a better track of them? 
This would help anyone interested in make these changes choose one to work on.

**Comment by abnersajr** [comment]
> How about we make an list of components that need be changed, for a better track of them?
> This would help anyone interested in make these changes choose one to work on.

Sure. This is the idea of the Roadmap. But it takes some time. If you have time available you can do it.
In case you can't edit the Original Post, add the components in a comment and I add to the post.

**Comment by Isaius** [comment]
I can't edit. I'll search a bit and then edit this comment to add them.

**Comment by abnersajr** [comment]
Thank you @Isaius for the contribution. The list was added to the issue. Just to not bloat the discussion, could you delete it please?

**Comment by Isaius** [comment]
Trying to make a test, figured out that in order to implements these changes, the way to extend the `JSX.IntrinsecElements['div']` is: 

```ts
type divProps = JSX.IntrinsicElements['div'];

export interface componentProps extends divProps {
      .....
}

declare const Component: React.FC<componentProps>;

export { Component };
```

TypeScript don't allow extend directly as in your example.

**Comment by abnersajr** [comment]
@Isaius thanks for the inputs. Looking around the codebase I se some places implementing the nomeclature of `<component>Type` for `export type <Component>Type = ...`
I updated the pattern and in case of multiple extends you will have:

```ts
export type AccordionType = BoxProps &
  AccordionProps &
  JSX.IntrinsicElements['div'];

declare const Accordion: React.FC<AccordionType>;
```

About the `JSX.IntrinsicElements` being extended twice, It's not a problem. If for some reason the `BoxProps` stops extending in their component, or we decide to not use `BoxProps` anymore, we still having this props.

**Comment by abnersajr** [comment]
@ericsoderberghp @ShimiSun and other contributors. I would like to hear your 10 cents about the pattern suggested.

**Comment by ericsoderberghp** [comment]
I believe that we need to revisit the approach taken in #4909 . If there are existing callers who have extended the current ComponentProps to add some instrinsic properties, I think their code will break due to the new properties already existing. I'm thinking we should preserve the existing behavior and add a new export for the extension:
```
export interface TextInputProps { ... };

export interface TextInputExtendedProps extends Omit<
JSX.IntrinsicElements['input'],
'onSelect' | 'size' | 'placeholder'
>, TextInputProps {};

declare const TextInput: React.FC<TextInputExtendedProps>;

export { TextInput };
```

**Comment by abnersajr** [comment]
Thank you for your input, @ericsoderberghp. Definitely, we need to take care of backward compatibility.
IMO, we could use your suggestion about adding new exports and signal users about this.
Can we add some tag of discussion, draft on the issue, please.

**Comment by ShimiSun** [comment]
@abnersajr thanks for owning this important enhancement buddy! This could improve the Grommet + TS experience.
I think our next step will be to add the Extended support to TextInput and roll back the changes from #4909 to be backward compatible.

**Comment by alexmirrington** [comment]
Just to jump in on the discussion, and perhaps provide a bit of perspective about what current users of the library might be doing, I'll provide an example of the custom component I was working on today: a heading component with a linear gradient. Today was my first day with React + Grommet + TypeScript. I'm a newbie and noticed that importing `HeadingProps` from Grommet didn't include any information about the all-important `children` prop, and it had be confused for a while. I delved into the source code a bit more, and alas, I saw a similar issue with non-included `JSX.IntrinsicElements` as showcased by @ericsoderberghp.

I'd love to contribute to this issue and get it into the primary source code ASAP, since I am currently doing this as a workaround:

```TypeScript
import { ThemeContext, Heading, HeadingProps as _HeadingProps } from "grommet";
import { ColorType, Omit } from "grommet/utils";
import React from "react";

// TODO: Import from grommet when types are more concrete,
// as discussed here: github.com/grommet/grommet/issues/4978
type HeadingProps = _HeadingProps &
  (
    | Omit<JSX.IntrinsicElements["h1"], "color">
    | Omit<JSX.IntrinsicElements["h2"], "color">
    | Omit<JSX.IntrinsicElements["h3"], "color">
    | Omit<JSX.IntrinsicElements["h4"], "color">
    | Omit<JSX.IntrinsicElements["h5"], "color">
    | Omit<JSX.IntrinsicElements["h6"], "color">
  );

export interface GradientHeadingProps extends HeadingProps {
  gradient: Array<ColorType>;
  angle?: number;
}

const themeExtension = {
  heading: {
    extend: (props: GradientHeadingProps) => {
      return `background-image: linear-gradient(${
        props.angle ?? 90
      }deg, ${props.gradient.join()});
      -webkit-background-clip: text;
      -moz-background-clip: text;
      -webkit-text-fill-color: transparent;
      -moz-text-fill-color: transparent;`;
    },
  },
};

const GradientHeading = (props: GradientHeadingProps): JSX.Element => {
  console.log(props);
  return (
    <ThemeContext.Extend value={themeExtension}>
      <Heading {...props}>{props.children}</Heading>
    </ThemeContext.Extend>
  );
};

export default GradientHeading;
```

**Comment by ShimiSun** [comment]
@alexmirrington thanks for your inputs! 

For your example, our thoughts were to allow export of "HeadingExtendedProps" in addition to exporting the existing "HeadingProps" that were already exported.
Feel free to make a contribution on Heading/index.d.ts to allow this type.

**Comment by abnersajr** [comment]
@ShimiSun @ericsoderberghp I've updated the ticket with the patterns discussed here.
I'm thinking in close this ticket and open a new one fresh, to better keep tracking the process.
About the [Rules for Migration](#rules-for-migration), do you agree?

**Comment by alexmirrington** [comment]
@ShimiSun I started working on implementing `HeadingExtendedProps` today, but ran into an issue that will pop up for other components and requires a bit of design:

> What is the best way to create an interface that extends a union of types?

For the `HeadingProps` example above, we can easily do something like the following:

```TypeScript
type OmitHeadingColor =
  | Omit<JSX.IntrinsicElements['h1'], 'color'>
  | Omit<JSX.IntrinsicElements['h2'], 'color'>
  | Omit<JSX.IntrinsicElements['h3'], 'color'>
  | Omit<JSX.IntrinsicElements['h4'], 'color'>
  | Omit<JSX.IntrinsicElements['h5'], 'color'>
  | Omit<JSX.IntrinsicElements['h6'], 'color'>;

export interface HeadingExtendedProps extends HeadingProps, OmitHeadingColor {};
```

I'd rather avoid creating an intermediate type that is not used, or at least I would like to move those types to some common area of the code base. If anyone more seasoned with TypeScript has some suggestions I'm all ears!

**Comment by ShimiSun** [comment]
> @ShimiSun @ericsoderberghp I've updated the ticket with the patterns discussed here.
> I'm thinking in close this ticket and open a new one fresh, to better keep tracking the process.
> About the migration rules, do you agree?

I agree and rooting for a new ticket to keep this one less bloatedd. Just make sure to link the TextInputProps PR and this issue to it.

**Comment by abnersajr** [comment]
Closed in favor of #4998
