### ISSUE TITLE
[TS]: Extended types export

### ISSUE THREAD

**Issue by abnersajr** [grommet/grommet#4998]
Pay attention to rules for migration at the end of the issue.
This is a tracking ticket for #4978 
### Expected Behavior

Be able to import and extend the `<component>Props` correctly, bringing the ` JSX.IntrinsicElements` props together.

### Actual Behavior

Components have theirs on `<component>Props` combined with ` JSX.IntrinsicElements` being exported using the `declare` block. The import of `<component>Props` doesn't have all the props defined in the `declare` block.

References:
https://github.com/grommet/grommet/pull/4909
https://github.com/grommet/grommet/issues/4976

### Proposed Solution

As discussed in the PR: https://github.com/grommet/grommet/pull/4909,
We need to check which components follow the pattern of combining the props on `declare` blocks.
A second item is that many components are defined as `React.ComponentClass` but can be modified to `React.FC`.

That being said, we should start refining these declarations following the examples below, where we create and export an extended version of the props instead of removing the actual export:

```ts
// another example
export interface TextInputProps { ... };

export interface TextInputExtendedProps extends Omit<
JSX.IntrinsicElements['input'],
'onSelect' | 'size' | 'placeholder'
>, TextInputProps {};

declare const TextInput: React.FC<TextInputExtendedProps>;

export { TextInput };
```

### Roadmap

Thanks to @Isaius for check and get this list for us.

 These do not extend `JSX.IntrinscElements` in their props interface but in the `declare` block.
 
- [x] [Accordion](https://github.com/grommet/grommet/blob/master/src/js/components/Accordion/index.d.ts) (#5010)
- [x] [AccordionPanel](https://github.com/grommet/grommet/blob/master/src/js/components/AccordionPanel/index.d.ts) (#5010)
- [x] [Anchor](https://github.com/grommet/grommet/blob/master/src/js/components/Anchor/index.d.ts)
- [x] [Avatar](https://github.com/grommet/grommet/blob/master/src/js/components/Avatar/index.d.ts)
- [x] [Carroussel](https://github.com/grommet/grommet/blob/master/src/js/components/Carousel/index.d.ts) (#5010)[ComponentClass]
- [x] [CheckBox](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBox/index.d.ts) (#5010)
- [x] [CheckBoxGroup](https://github.com/grommet/grommet/blob/master/src/js/components/CheckBoxGroup/index.d.ts)
- [x] [Clock](https://github.com/grommet/grommet/blob/master/src/js/components/Clock/index.d.ts)
- [x] [Collapsible](https://github.com/grommet/grommet/blob/master/src/js/components/Collapsible/index.d.ts)
- [x] [DataTable](https://github.com/grommet/grommet/blob/master/src/js/components/DataTable/index.d.ts)
- [x] [Diagram](https://github.com/grommet/grommet/blob/master/src/js/components/Diagram/index.d.ts) (#5021)
- [x] [Distribution](https://github.com/grommet/grommet/blob/master/src/js/components/Distribution/index.d.ts) (#5021)
- [x] [DropButton](https://github.com/grommet/grommet/blob/master/src/js/components/DropButton/index.d.ts) (#5021)
- [x] [FileInput](https://github.com/grommet/grommet/blob/master/src/js/components/FileInput/index.d.ts)(#5021)
- [x] [FormField](https://github.com/grommet/grommet/blob/master/src/js/components/FormField/index.d.ts)
- [x] [Grid](https://github.com/grommet/grommet/blob/master/src/js/components/Grid/index.d.ts)
- [x] [Grommet](https://github.com/grommet/grommet/blob/master/src/js/components/Grommet/index.d.ts)
- [x] [Heading](https://github.com/grommet/grommet/blob/master/src/js/components/Heading/index.d.ts) (#4995)
- [x] [Image](https://github.com/grommet/grommet/blob/master/src/js/components/Image/index.d.ts)
- [x] [Layer](https://github.com/grommet/grommet/blob/master/src/js/components/Layer/index.d.ts)
- [x] [List](https://github.com/grommet/grommet/blob/master/src/js/components/List/index.d.ts)
- [x] [Markdown](https://github.com/grommet/grommet/blob/master/src/js/components/Markdown/index.d.ts) (#4995)
- [x] [MaskedInput](https://github.com/grommet/grommet/blob/master/src/js/components/MaskedInput/index.d.ts)
- [x] [Paragraph](https://github.com/grommet/grommet/blob/master/src/js/components/Paragraph/index.d.ts) (#4995)
- [x] [RadioButton](https://github.com/grommet/grommet/blob/master/src/js/components/RadioButton/index.d.ts) (#5018)
- [x] [RadioButtonGroup](https://github.com/grommet/grommet/blob/master/src/js/components/RadioButtonGroup/index.d.ts) (#5018)
- [x] [RangeInput](https://github.com/grommet/grommet/blob/master/src/js/components/RangeInput/index.d.ts) (#5018)
- [x] [RangeSelector](https://github.com/grommet/grommet/blob/master/src/js/components/RangeSelector/index.d.ts) (#5018)
- [x] [SideBar](https://github.com/grommet/grommet/blob/master/src/js/components/Sidebar/index.d.ts) (#5016)
- [x] [Stack](https://github.com/grommet/grommet/blob/master/src/js/components/Stack/index.d.ts) (#5016)
- [x] [Tab](https://github.com/grommet/grommet/blob/master/src/js/components/Tab/index.d.ts) (#5016)
- [x] [Table](https://github.com/grommet/grommet/blob/master/src/js/components/Table/index.d.ts)(#5008)
- [x] [TableBody](https://github.com/grommet/grommet/blob/master/src/js/components/TableBody/index.d.ts)(#5008)
- [x] [TableCell](https://github.com/grommet/grommet/blob/master/src/js/components/TableCell/index.d.ts)(#5009)
- [x] [TableFooter](https://github.com/grommet/grommet/blob/master/src/js/components/TableFooter/index.d.ts)(#5008)
- [x] [TableHeader](https://github.com/grommet/grommet/blob/master/src/js/components/TableHeader/index.d.ts)(#5008)
- [x] [TableRow](https://github.com/grommet/grommet/blob/master/src/js/components/TableRow/index.d.ts)(#5009)
- [x] [Tabs](https://github.com/grommet/grommet/blob/master/src/js/components/Tabs/index.d.ts) (#5016)
- [x] [Text](https://github.com/grommet/grommet/blob/master/src/js/components/Text/index.d.ts) (#4995)
- [x] [TextArea](https://github.com/grommet/grommet/blob/master/src/js/components/TextArea/index.d.ts)
- [x] [Video](https://github.com/grommet/grommet/blob/master/src/js/components/Video/index.d.ts)
- [x] [WorldMap](https://github.com/grommet/grommet/blob/master/src/js/components/WorldMap/index.d.ts)
 
 These are OK, but do not follow the pattern, using Type instead interface:
 
- [x] [Box](https://github.com/grommet/grommet/blob/master/src/js/components/Box/index.d.ts)
- [x] [Button](https://github.com/grommet/grommet/blob/master/src/js/components/Button/index.d.ts)
- [x] [Calendar](https://github.com/grommet/grommet/blob/master/src/js/components/Calendar/index.d.ts)
- [x] [Drop](https://github.com/grommet/grommet/blob/master/src/js/components/Drop/index.d.ts)
 
 Only ComponentClass, but not wrong:
 
- [x] [Chart](https://github.com/grommet/grommet/blob/master/src/js/components/Chart/index.d.ts)

### Rules for Migration

- Pick a maximum of **4 components** at the same time
- Comment which one you will work
- Work is done! Create the PR with a **maximum of 4 components per PR**
- Wait for the review and the merge. After merged, you can pick new ones.

**Comment by alexmirrington** [comment]
These last five PRs should cover the rest of the components in the list above, as well as a few extras that should be using `React.FC` instead of `React.ComponentClass` for the component type. When doing these last few issues, I noticed lots of components like `Card` etc. use `BoxTypes` directly, since they are essentially boxes. Should we be adding aliases like `CardProps` and `CardExtendedProps` in these cases for consistency?

**Comment by ShimiSun** [comment]
>When doing these last few components, I noticed lots of components like Card etc. use BoxTypes directly, since they are essentially boxes. Should we be adding aliases like CardProps and CardExtendedProps in these cases for consistency?

How would adding the aliases make our work more consistent? Can you share an example on how you think the current approach could be improved?

**Comment by alexmirrington** [comment]
@ShimiSun Consider the `Card` component for example; the `index.d.ts` file for the `Card` component contains the following:

```TypeScript
import * as React from 'react';
import { BoxTypes } from '../Box';

declare const Card: React.FC<BoxTypes>;

export { Card };
```

Since the `Card` component has type `React.FC<BoxTypes>`, users of Grommet will be inclined to import `BoxTypes` directly wen extending the `Card` component to fit their needs. For example, if someone wanted to extend the `Card` component to support a linear gradient background, they would make a new interface `GradientCardProps` that extends `BoxTypes` like so:

```TypeScript
export interface GradientCardProps extends BoxTypes {
  gradient: ColorType[];
  angle?: number;
}
```

The following has two primary issues:

1. It is is a little cryptic to users of grommet to have a custom `CardProps` interface extend something labelled like `BoxTypes`.
2. It will create extra work for the Grommet team in the future if the `Card` component ever has additional props on top of those defined in `BoxTypes`. Suddenly, we will need to create a `CardProps` and `CardExtendedProps` interface, and somehow communicate to Grommet users that they should be using `CardExtendedProps` instead of `BoxTypes`.

To address these issues, I'd suggest exporting `CardProps` and `CardExtendedProps` like we have for other components, _e.g._:

``Typescript

import * as React from 'react';
import { BoxTypes } from '../Box';

export interface CardProps {}
export interface CardExtendedProps extends CardProps, BoxTypes {}

declare const Card: React.FC<CardExtendedProps>;

export { Card };

````

**Comment by ShimiSun** [comment]
Fantastic work team!! It was a pleasure working & learning from you all ❤️  
Obrigada!
