### ISSUE TITLE
Tracking removal of react-desc

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet#5353]
### Expected Behavior
`react-desc` should be removed from grommet and the documentation for each component should be contained in the grommet-site repo.

Original discussion about removing `react-desc` #2976 

### Actual Behavior
Grommet is using `react-desc` for documentation and the docs are in the grommet repo

### Steps:
In the steps below replace <component> with the name of the component you are changing. Pull requests should be submitted per component.

**Grommet-site**
Ensure the component has been transitioned to the new documentation format on the grommet site. This must be done BEFORE the doc is removed on grommet. See https://github.com/grommet/grommet-site/issues/233 to determine which components are using the new documentation format and can safely have their doc removed from grommet

Note: as of 7/29 all components have been transitioned to the new format for documentation on grommet-site

**Grommet**
Example pull request: https://github.com/grommet/grommet/pull/5492

1. Create a new file `src/js/components/<component>/propTypes.js`
2. Add `import PropTypes from 'prop-types';` to the propTypes file.
3. If necessary add any imports needed from `../../utils/general-prop-types'` to the propTypes file.
4. In the propTypes file add the propTypes that are defined in `src/js/components/<component>/doc.js`.
5. Export the propTypes in the propTypes file as `<component>Type`. (ex. AnchorType).
6. In the `src/js/components/<component>/<component>.js` file add `import { <component>Type } from './propTypes';`
7. Remove code referencing the component documentation from the `<component>.js` file.
  Example for the Anchor component remove the following:
    ```
    let AnchorDoc;
    if (process.env.NODE_ENV !== 'production') {
    // eslint-disable-next-line global-require
    AnchorDoc = require('./doc').doc(Anchor);
    }
    const AnchorWrapper = AnchorDoc || Anchor;
    
    export { AnchorWrapper as Anchor };
    ```
    replace with:
    ```
    <component>.propTypes = <component>Type;
    export { <component> };
    ``` 
9. Remove `src/js/components/<component>/doc.js`.
10. Replace the contents of the `src/js/components/<component>/README.md` file with 
    ```
    ## <component>
    Documentation for this component: https://v2.grommet.io/<component>
    ```
11. Run `yarn test-update`. The snapshots for `README-test` and `components-test` should be updated.

## Components
List for tracking which components have had `react-desc` removed from them:

- [x] Accordion
- [x] AccordionPanel
- [x] Anchor
- [x] Avatar
- [x] Box
- [x] Button
- [x] Calendar
- [x] Card, CardBody, CardFooter & CardHeader (should be done together)
- [x] Carousel
- [x] CheckBoxGroup
- [x] Chart
- [x] CheckBox
- [x] Clock
- [x] Collapsible
- [x] DataChart
- [x] DataTable
- [x] DateInput
- [x] Diagram
- [x] Distribution
- [x] Drop
- [x] DropButton
- [x] FileInput
- [x] Footer
- [x] Form
- [x] FormField
- [x] Grid
- [x] Grommet
- [x] Header
- [x] Heading
- [x] Image
- [x] InfiniteScroll
- [x] Keyboard
- [x] Layer
- [x] List
- [x] Main
- [x] Markdown
- [x] MaskedInput
- [x] Menu
- [x] Meter
- [x] Pagination
- [x] Paragraph
- [x] Nav
- [x] RadioButton
- [x] RadioButtonGroup
- [x] RangeInput
- [x] RangeSelector
- [x] RoutedAnchor (special case, not on grommet-site)
- [x] RoutedButton (special case, not on grommet-site)
- [x] Select
- [x] Sidebar
- [x] SkipLinks
- [x] Spinner
- [x] Stack
- [x] Table, TableBody, TableCell, TableFooter, TableHeader, & TableRow (should be done together)
- [x] Tab & Tabs (should be done together)
- [x] Text
- [x] TextArea
- [x] TextInput
- [x] Tip
- [x] Video
- [x] WorldMap
