### ISSUE TITLE
[TS] Migrate tests to .tsx

### ISSUE THREAD

**Issue by alexmirrington** [grommet/grommet#5599]
### Overview and Motivation

This is a ticket to aid the migration of `*.js` tests to `*.tsx`. The general motivation here is to improve TypeScript support in Grommet so that when type checks fail, so do unit tests. For more details about why and how we are doing this, please refer to the related Issues and PRs below.

### Related Issues and PRs

Addition of TS unit testing support:

- Issue: #5111
- PR: #5589

### Contributing

 Since we have close to 75 components now and the tests for each range from simple to quite complex, It makes sense to migrate a single component at a time to `*.tsx` files, taking a test-driven development (TDD) approach.

- Pick a single component at a time to work on test migrations for.
- Create a draft PR while you work on the components tests. Mention this issue in the PR to make sure multiple people don't double up on a single component.
- Rename the tests for that component from `*-test.js` to `*-test.tsx`
- Rename the `*-test.js.snap` files for that component to `*-test.tsx.snap`
- Run the test suite for that component with `yarn test`. No test snapshots should fail, but some tests might fail due to type check failures.
- If migrating tests causes only a few Typescript errors (_e.g._ missing field on prop types), feel free to fix those issues in the same PR as the test migration **including the test failure and an explanation about how the changes fix the test failure.** If there are a lot of new errors, create separate issues for each error and fix them in a separate PR. Update the test migration branch with these changes until the tests pass.

### Roadmap

Test migration completed for:

- [x] Accordion #5609 
- [x] AccordionPanel #5610
- [x] Anchor #5600
- [x] Avatar #5602
- [x] Box #5611
- [x] Button #5645
- [x] Calendar #5656
- [x] Card #5612
- [x] ~~CardBody~~ No tests to migrate
- [x] ~~CardFooter~~ No tests to migrate
- [x] ~~CardHeader~~ No tests to migrate
- [x] Carousel #5643
- [x] Chart https://github.com/grommet/grommet/pull/6192
- [x] CheckBox #5644
- [x] CheckBoxGroup #5653
- [x] Clock #5655
- [x] Collapsible #5686
- [x] DataChart #6377
- [x] DataTable
- [x] DateInput #5696
- [x] Diagram #5759 
- [x] Distribution #6378
- [x] Drop #5714 
- [x] DropButton #6379
- [x] FileInput #5696
- [x] Footer #5703
- [x] Form
- [x] FormField
- [ ] Grid
- [ ] Grommet
- [x] Header #5701
- [x] Heading #5723 
- [x] Image #5704
- [x] InfiniteScroll #5718 
- [x] Keyboard #5748 
- [ ] Layer
- [x] List
- [x] Main #5685
- [x] Markdown
- [x] MaskedInput
- [ ] Menu
- [x] Meter #5690
- [x] NameValueList #5626
- [x] NameValuePair #5626
- [x] Nav #5719 
- [x] Notification
- [x] Page #5960
- [x] ~~PageContent~~ No tests to migrate
- [x] PageHeader #6071
- [x] Pagination #5722 
- [x] Paragraph #5724 
- [x] RadioButton #5720 
- [x] RadioButtonGroup #5721 
- [x] RangeInput #5690
- [x] RangeSelector
- [x] ~~RoutedAnchor~~ Deprecated
- [x] ~~RoutedButton~~ Deprecated
- [ ] Select
- [x] SelectMultiple #6725
- [x] Sidebar #6382
- [x] ~~SkipLink~~ No tests to migrate
- [x] SkipLinks
- [x] ~~SkipLinkTarget~~ No tests to migrate
- [x] Spinner #5702
- [x] Stack #5743 
- [x] ~~Tab~~ No tests to migrate
- [x] Table #5746 
- [x] ~~TableBody~~ No tests to migrate
- [x] ~~TableCell~~ No tests to migrate
- [x] ~~TableFooter~~ No tests to migrate
- [x] ~~TableHeader~~ No tests to migrate
- [x] ~~TableRow~~ No tests to migrate
- [x] Tabs #5659 #5732
- [x] Tag #5778
- [x] Text #5725 
- [x] TextArea #6381
- [x] TextInput #5749 
- [x] Tip #5763
- [x] Video #6380
- [x] WorldMap #5654

**Comment by alexmirrington** [comment]
Hi @jcfilben and @ericsoderberghp,

I was just wondering what approach you would recommend for components that currently dont have tests associated with them such as `AccordionPanel`, `CardHeader`, `CardBody` and `CardFooter`?

As discussed in issue #5610, I wonder if `AccordionPanel` tests should reside under the `AccordionPanel` component rather than `Accordion`, or whether including tests under `Accordion` is intentional. The same goes for `CardHeader`, `CardBody` and `CardFooter` tests being grouped under the `Card` component.

I'm happy if you want to keep tests where they are at the moment, if so I'll cross these components off the list as we will only need to migrate the tests for parent components.

Cheers,
Alex.

**Comment by jcfilben** [comment]
I am leaning towards just keeping tests under the parent component

**Comment by alexmirrington** [comment]
@jcfilben Just updated the list of components above in preparation for Hacktoberfest to include new components that have been implemented in the last year. Looks like they have all been written with TypeScript tests from the start which is awesome to see!

**Comment by jcfilben** [comment]
> @jcfilben Just updated the list of components above in preparation for Hacktoberfest to include new components that have been implemented in the last year. Looks like they have all been written with TypeScript tests from the start which is awesome to see!

Perfect, thanks for updating the list to include the new components! And yes, we've been making an effort to have any new testing files written in typescript

**Comment by nishantdecode** [comment]
is this issue officially closed and not accepting anymore PR's ?

**Comment by jcfilben** [comment]
No, it looks like #7337 has the 'fixes' keyword which closed this issue once the PR was merged. I'll re-open the issue

**Comment by radheshpai87** [comment]
Is this issue still active as the ones that are not checked are also having tsx files.

**Comment by britt6612** [comment]
@radheshpai87 

Yes this issue is still active I have updated the list to reflect todays files that still need changed
